# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lsh < Formula
  desc ""
  homepage "https://www.latitude.sh/"
  version "1.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/latitudesh/lsh/releases/download/v1.3.1/lsh_Darwin_x86_64.tar.gz"
      sha256 "91cc617163373b36092a171a70791b90a11a965f339e044b4cd896e6b2867924"

      def install
        bin.install "lsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/latitudesh/lsh/releases/download/v1.3.1/lsh_Darwin_arm64.tar.gz"
      sha256 "deef18b696432d72ee1000fabb8ea8ee7cb5523152d46d5d640b886d988c0111"

      def install
        bin.install "lsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/latitudesh/lsh/releases/download/v1.3.1/lsh_Linux_x86_64.tar.gz"
      sha256 "6052192d15e88f3ed02eeb884bdcb9e92e1b32ea9c15cee21ed08139eeaa7834"

      def install
        bin.install "lsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/latitudesh/lsh/releases/download/v1.3.1/lsh_Linux_arm64.tar.gz"
      sha256 "c7adc4aefc046cd4baaf00d123a64957a16859c67190a944e9b4a4cc1ad4bc4a"

      def install
        bin.install "lsh"
      end
    end
  end
end
