# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lsh < Formula
  desc ""
  homepage "https://www.latitude.sh/"
  version "1.4.0"

  on_macos do
    on_intel do
      url "https://github.com/latitudesh/cli/releases/download/v1.4.0/cli_Darwin_x86_64.tar.gz"
      sha256 "803b054e43d14d52ccaca4e64a6a545e719fc950000bdadb731117b2b06f7dfc"

      def install
        bin.install "cli"
      end
    end
    on_arm do
      url "https://github.com/latitudesh/cli/releases/download/v1.4.0/cli_Darwin_arm64.tar.gz"
      sha256 "dcaa224b97ceb3b143d88a26b244ad427e0e8b502f7401c3bdbcd7be041c861d"

      def install
        bin.install "cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/latitudesh/cli/releases/download/v1.4.0/cli_Linux_x86_64.tar.gz"
        sha256 "2c2f18696ef4108218fa394a1a58480f6dc0f69943ab6881eaa768ce342a8b70"

        def install
          bin.install "cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/latitudesh/cli/releases/download/v1.4.0/cli_Linux_arm64.tar.gz"
        sha256 "ae56c077c0a31570aed2e3792e350d81bb16fa994b4b87d115d7f0c68a092275"

        def install
          bin.install "cli"
        end
      end
    end
  end
end
